# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

language: julia

os:
  - linux

julia:
  - 1.1

before_script:
  - julia --color=yes -e 'using Pkg; pkg"add Flux#master"'
  - julia --color=yes -e 'using Pkg; pkg"add ImageFiltering#master"'

script:
  - JIVE_PROCS=auto julia --color=yes -e 'using Pkg; Pkg.test()'
